/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package intro.di

import java.lang.Boolean.TRUE
import kotlin.test.Test
import kotlin.test.assertTrue

class LibraryTest {
    @Test fun testSomeLibraryMethod() {
        assertTrue(TRUE, "someLibraryMethod should return 'true'")
    }
}
